//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvSon.Models.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbcvEntities : DbContext
    {
        public dbcvEntities()
            : base("name=dbcvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_DENEYIM> TBL_DENEYIM { get; set; }
        public virtual DbSet<TBL_EGITIM> TBL_EGITIM { get; set; }
        public virtual DbSet<TBL_HAKKINDA> TBL_HAKKINDA { get; set; }
        public virtual DbSet<TBL_HOBILER> TBL_HOBILER { get; set; }
        public virtual DbSet<TBL_ILETISIM> TBL_ILETISIM { get; set; }
        public virtual DbSet<TBL_SERTIFIKA> TBL_SERTIFIKA { get; set; }
        public virtual DbSet<TBL_YETENEKLER> TBL_YETENEKLER { get; set; }
        public virtual DbSet<TBLSOSYALMEDYA> TBLSOSYALMEDYA { get; set; }
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
    }
}
